In [14]:
import numpy as np
import pandas as pd
import sklearn as skl
import matplotlib
from sklearn import svm

NameError: name 'read' is not defined

In [ ]:
data = pd.read_csv("african_crises.csv")

case  cc3   country  year  systemic_crisis    exch_usd  \
0        1  DZA   Algeria  1870                1    0.052264   
1        1  DZA   Algeria  1871                0    0.052798   
2        1  DZA   Algeria  1872                0    0.052274   
3        1  DZA   Algeria  1873                0    0.051680   
4        1  DZA   Algeria  1874                0    0.051308   
...    ...  ...       ...   ...              ...         ...   
1054    70  ZWE  Zimbabwe  2009                1  354.800000   
1055    70  ZWE  Zimbabwe  2010                0  378.200000   
1056    70  ZWE  Zimbabwe  2011                0  361.900000   
1057    70  ZWE  Zimbabwe  2012                0  361.900000   
1058    70  ZWE  Zimbabwe  2013                0  361.900000   

      domestic_debt_in_default  sovereign_external_debt_default  \
0                            0                                0   
1                            0                                0   
2                            0                                0   
3                            0                                0   
4                            0                                0   
...                        ...                              ...   
1054                         1                                1   
1055                         1                                1   
1056                         1                                1   
1057                         1                                1   
1058                         1                                1   

      gdp_weighted_default  inflation_annual_cpi  independence  \
0                      0.0              3.441456             0   
1                      0.0             14.149140             0   
2                      0.0             -3.718593             0   
3                      0.0             11.203897             0   
4                      0.0             -3.848561             0   
...                    ...                   ...           ...   
1054                   0.0             -7.670000             1   
1055                   0.0              3.217000             1   
1056                   0.0              4.920000             1   
1057                   0.0              3.720000             1   
1058                   0.0              1.632000             1   

      currency_crises  inflation_crises banking_crisis  
0                   0                 0         crisis  
1                   0                 0      no_crisis  
2                   0                 0      no_crisis  
3                   0                 0      no_crisis  
4                   0                 0      no_crisis  
...               ...               ...            ...  
1054                1                 0         crisis  
1055                0                 0      no_crisis  
1056                0                 0      no_crisis  
1057                0                 0      no_crisis  
1058                0                 0      no_crisis  

[1059 rows x 14 columns]

In [16]:
np.unique(data["country"].values, return_counts=True)


(array(['Algeria', 'Angola', 'Central African Republic', 'Egypt',
        'Ivory Coast', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
        'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object),
 array([ 85,  77,  58, 155,  63,  67,  68,  75,  60, 114,  75,  72,  90],
       dtype=int64))

In [47]:
Morocco = data[data.country == "Morocco"]
Zimbabve = data[data.country == "Zimbabve"]
Algeria = data[data.country == "Algeria"]
Angola = data[data.country == "Angola"]
Central_African_Republic = data[data.country == "Central African Republic"]
Ivory_Coast = data[data.country == "Ivory Coast"]
Egypt = data[data.country == "Egypt"]
Kenya = data[data.country == "Kenya"]
Mauritius = data[data.country == "Mauritius"]
Nigeria = data[data.country == "Nigeria"]
South_Africa = data[data.country == "South Africa"]
Tunisia = data[data.country == "Tunisia"]
Zambia = data[data.country == "Zambia"]
Zimbabve = data[data.country == "Zimbabve"]
country, cnt = np.unique(data["systemic_crisis"].values, return_counts = True)

In [49]:
cnt

array([977,  82], dtype=int64)

In [28]:
Morocco = data[data.country == "Morocco"]
Morocco
               


case  cc3  country  year  systemic_crisis  exch_usd  \
573    40  MAR  Morocco  1940                0    0.9170   
574    40  MAR  Morocco  1941                0    0.9170   
575    40  MAR  Morocco  1942                0    0.7500   
576    40  MAR  Morocco  1943                0    0.5000   
577    40  MAR  Morocco  1944                0    0.5674   
..    ...  ...      ...   ...              ...       ...   
643    40  MAR  Morocco  2010                0    8.3569   
644    40  MAR  Morocco  2011                0    8.5772   
645    40  MAR  Morocco  2012                0    8.4335   
646    40  MAR  Morocco  2013                0    8.1500   
647    40  MAR  Morocco  2014                0    8.8200   

     domestic_debt_in_default  sovereign_external_debt_default  \
573                         0                                0   
574                         0                                0   
575                         0                                0   
576                         0                                0   
577                         0                                0   
..                        ...                              ...   
643                         0                                0   
644                         0                                0   
645                         0                                0   
646                         0                                0   
647                         0                                0   

     gdp_weighted_default  inflation_annual_cpi  independence  \
573                   0.0             25.000000             0   
574                   0.0             32.000000             0   
575                   0.0             38.193529             0   
576                   0.0             28.506356             0   
577                   0.0             34.811640             0   
..                    ...                   ...           ...   
643                   0.0              0.994000             1   
644                   0.0              0.907000             1   
645                   0.0              1.287000             1   
646                   0.0              1.881000             1   
647                   0.0              0.443000             1   

     currency_crises  inflation_crises banking_crisis  
573                0                 1      no_crisis  
574                0                 1      no_crisis  
575                0                 1      no_crisis  
576                1                 1      no_crisis  
577                1                 1      no_crisis  
..               ...               ...            ...  
643                0                 0      no_crisis  
644                0                 0      no_crisis  
645                0                 0      no_crisis  
646                0                 0      no_crisis  
647                0                 0      no_crisis  

[75 rows x 14 columns]

In [37]:
Morocco.head(6)


case  cc3  country  year  systemic_crisis  exch_usd  \
573    40  MAR  Morocco  1940                0    0.9170   
574    40  MAR  Morocco  1941                0    0.9170   
575    40  MAR  Morocco  1942                0    0.7500   
576    40  MAR  Morocco  1943                0    0.5000   
577    40  MAR  Morocco  1944                0    0.5674   
578    40  MAR  Morocco  1945                0    0.5657   

     domestic_debt_in_default  sovereign_external_debt_default  \
573                         0                                0   
574                         0                                0   
575                         0                                0   
576                         0                                0   
577                         0                                0   
578                         0                                0   

     gdp_weighted_default  inflation_annual_cpi  independence  \
573                   0.0             25.000000             0   
574                   0.0             32.000000             0   
575                   0.0             38.193529             0   
576                   0.0             28.506356             0   
577                   0.0             34.811640             0   
578                   0.0             18.986181             0   

     currency_crises  inflation_crises banking_crisis  
573                0                 1      no_crisis  
574                0                 1      no_crisis  
575                0                 1      no_crisis  
576                1                 1      no_crisis  
577                1                 1      no_crisis  
578                0                 0      no_crisis

In [39]:
Morocco = data[data.country == "Morocco"]
Zimbabve = data[data.country == "Zimbabve"]
Algeria = data[data.country == "Algeria"]
Angola = data[data.country == "Angola"]
Central_African_Republic = data[data.country == "Central African Republic"]
Ivory_Coast = data[data.country == "Ivory Coast"]
Egypt = data[data.country == "Egypt"]
Kenya = data[data.country == "Kenya"]
Mauritius = data[data.country == "Mauritius"]
Nigeria = data[data.country == "Nigeria"]
South_Africa = data[data.country == "South Africa"]
Tunisia = data[data.country == "Tunisia"]
Zambia = data[data.country == "Zambia"]
Zimbabve = data[data.country == "Zimbabve"]
country, cnt = np.unique(data["systemic_crisis"].values, return_counts = True)



array([0, 1], dtype=int64)

In [44]:
country, cnt = np.unique(data["systemic_crisis"].values, return_counts = True)


In [45]:
country


array([0, 1], dtype=int64)

In [46]:
cnt

array([977,  82], dtype=int64)